name: Build Go Program

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Automatically trigger on merges to the 'main' branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.20.3]  # Change to your desired Go version
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build for ${{ matrix.os }}
      run: GOOS=$(echo ${{ matrix.os }} | tr '[:lower:]' '[:upper:]') go build -o libby-chapterizer_${{ matrix.os }}

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: libby-chapterizer_${{ matrix.os }}
        path: ./libby-chapterizer_${{ matrix.os }}

    - name: Save binary
      run: mv libby-chapterizer_${{ matrix.os }} $GITHUB_WORKSPACE/libby-chapterizer_${{ matrix.os }}

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: libby-chapterizer_${{ matrix.os }}
        path: $GITHUB_WORKSPACE/libby-chapterizer_${{ matrix.os }}
