name: Build Go Program

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Automatically trigger on merges to the 'main' branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.21.3']  # Change to your desired Go version
        os: [linux, macos, windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build for ${{ matrix.os }}
      run: |

        if [ ! -d "build" ]; then
          mkdir ./build
        fi
        
        case ${{ matrix.os }} in
          'windows')
            GOOS=windows GOARCH=amd64 go build -o ./build/libby-chapterizer_windows.exe
            ;;
          'linux')
            GOOS=linux GOARCH=amd64 go build -o ./build/libby-chapterizer_linux
            chmod +x ./build/libby-chapterizer_linux
            ;;
          'macos')
            GOOS=darwin GOARCH=amd64 go build -o ./build/libby-chapterizer_macos
            chmod +x ./build/libby-chapterizer_macos
            ;;
        esac

    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: libby-chapterizer
        path: build/*
